spring:
  application:
      name: GREET-API
  boot:
    admin:
      client:
        url: http://localhost:9090

server:
  port: 2222

management:
  web:
    endpoints:
      exposure:
        include: "*"

