spring:
  application:
    name: Security-JDBC-Authentication
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Root@123
    url: jdbc:mysql://localhost:3306/Dammy
  jpa:
    show-sql: true
