spring:
    application.name:  WELCOME-API

    boot:
        admin:
            client:
                url: http://localhost:9090/
server:
    port: 1111

management:
    endpoints:
        web:
            exposure:
               include: "*"

